  
//
// Copyright 2003 P&P Software GmbH - All Rights Reserved
//
// TestCaseSampleR1Database_1.h
//
// This file was automatically generated by an XSL program
//

#ifndef TestCaseSampleR1Database_1H
#define TestCaseSampleR1Database_1H

#include "../Utilities/TestCaseWithEvtCheck.h"

/**
 * Verify the functionalities implemented by the
 * <code>DC_SampleR1Database</code> component.
 * An instance of the component is created and the following
 * specific tests are performed upon it: <ol>
 * <li>It is verified that the class ID of the component has the correct 
 * value.</li>
 * <li>It is verified that, after instantiation, the configuration service
 * of the component reports "not configured".</li>
 * <li>The component is configured and it is verified that the configuration service
 * of the component reports "configured".</li>
 * <li>It is verified that the operational table is initialized to hold a copy
 * of the default table.</li>
 * <li>The setter and getter methods for all parameter types are verified.</li>
 * <li>The pointer getter methods for all parameter types are verified.</li>  
 * </ol>
 * Note that the code for this test class - like the code for the component it tests -
 * is automatically generated by an XSLT program. The XSLT program takes as an input an
 * XML file (the 'Parameter Database Descriptor File') that describes the structure
 * of the database encapsulated in the component being tested.
 * @see DC_SampleR1Database
 * @author Alessandro Pasetti (P&P Software GmbH)
 * @version 1.0
 */
class TestCaseSampleR1Database_1 : public TestCaseWithEvtCheck {

public :

     /**
      * Set the identifier and the name of the test case to: 
      * ID_SAMPLER1DATABASE*10+1 and "TestCaseSampleR1Database_1".
      */
     TestCaseSampleR1Database_1();

     /**
      * Execute the test case. See class comment for details.
      */
      virtual void runTestCase();
};

#endif
