  
//
// Copyright 2003 P&P Software GmbH - All Rights Reserved
//
// TestCaseSampleR3Database_1.h
//
// This file was automatically generated by an XSL program
//

#ifndef TestCaseSampleR3Database_1H
#define TestCaseSampleR3Database_1H

#include "../Utilities/TestCaseWithEvtCheck.h"

/**
 * Verify the functionalities implemented by the
 * <code>DC_SampleR3Database</code> component.
 * An instance of the component is created and the following
 * specific tests are performed upon it: <ol>
 * <li>It is verified that the class ID of the component has the correct 
 * value.</li>
 * <li>It is verified that, after instantiation, the configuration service
 * of the component reports "not configured".</li>
 * <li>The component is configured and it is verified that the configuration service
 * of the component reports "configured".</li>
 * <li>It is verified that the operational table is initialized to hold a copy
 * of the default table.</li>
 * <li>The setter and getter methods for all parameter types are verified.</li>
 * <li>The pointer getter methods for all parameter types are verified.</li>  
 * <li>Non-nominal behaviour check: it is verified that a call to a setter method with an illegal
 * parameter identifier results in the generation of an "illegal database access" event 
 * report.  </li>
 * <li>Non-nominal behaviour check: it is verified that a call to a pointer getter method with an illegal
 * parameter identifier results in the generation of an "illegal database access" event 
 * report.  </li>
   
 * <li>Non-nominal behaviour check: it is verified that a call to a getter method with an illegal
 * parameter identifier results in the generation of "illegal database access" event 
 * report.  </li>
   
 * </ol>
 * Note that the code for this test class - like the code for the component it tests -
 * is automatically generated by an XSLT program. The XSLT program takes as an input an
 * XML file (the 'Parameter Database Descriptor File') that describes the structure
 * of the database encapsulated in the component being tested.
 * @see DC_SampleR3Database
 * @author Alessandro Pasetti (P&P Software GmbH)
 * @version 1.0
 */
class TestCaseSampleR3Database_1 : public TestCaseWithEvtCheck {

public :

     /**
      * Set the identifier and the name of the test case to: 
      * ID_SAMPLER3DATABASE*10+1 and "TestCaseSampleR3Database_1".
      */
     TestCaseSampleR3Database_1();

     /**
      * Execute the test case. See class comment for details.
      */
      virtual void runTestCase();
};

#endif
