  
//
// Copyright 2003 P&P Software GmbH - All Rights Reserved
//
// TestCaseSampleR3Database_1.cpp
//
// This file was automatically generated by an XSL program
//

#include "../GeneralInclude/CompilerSwitches.h"
#include "../GeneralInclude/ClassId.h"
#include "../GeneralInclude/Constants.h"
#include "../Data/DC_SampleR3Database.h"
#include "TestCaseSampleR3Database_1.h"
#include "../Utilities/TestCaseWithEvtCheck.h"

#include <math.h>
#include <float.h>

TestCaseSampleR3Database_1::TestCaseSampleR3Database_1():
	TestCaseWithEvtCheck(ID_SAMPLER3DATABASE*10+1,"TestCaseSampleR3Database_1") {
		return;
}

void TestCaseSampleR3Database_1::runTestCase() {

   // Data structures to simulate the default and operational tables
   // (The size of the database is read from the Parameter Database
   // Descriptor file).
   unsigned int dbLength = 80;
   unsigned char* defaultTable = new unsigned char[dbLength];
   unsigned char* operationalTable = new unsigned char[dbLength];

   // Initialize the default database. Each parameter is given a
   // value equal to its parameter ID. The parameter ID is read from
   // the Parameter Database Descriptor File. Note that this
   // strategy will sometimes result in an attempt to assign to a
   // parameter a value that is inconsistent with its type (e.g. a
   // a parameter of type 'char' might have a parameter ID greater than
   // 256).
   unsigned char* uc;
   
   uc = (defaultTable+0);
   *(short*)uc = (short)1;
   uc = (defaultTable+8);
   *(unsigned short*)uc = (unsigned short)2;
   uc = (defaultTable+16);
   *(int*)uc = (int)3;
   uc = (defaultTable+24);
   *(unsigned int*)uc = (unsigned int)4;
   uc = (defaultTable+32);
   *(char*)uc = (char)5;
   uc = (defaultTable+40);
   *(unsigned char*)uc = (unsigned char)6;
   uc = (defaultTable+48);
   *(float*)uc = (float)7;
   uc = (defaultTable+56);
   *(double*)uc = (double)8;
   uc = (defaultTable+64);
   *(bool*)uc = (bool)9;

   // Get current number of events in event repository
   unsigned int nEvt;
   nEvt = getNumberOfEvents();

   // Initialize the operational database to all zeros
   for (unsigned int i=0; i<dbLength; i++)
       operationalTable[i]=0;

   // Instantiate parameter database
   DC_SampleR3Database* pDB = new DC_SampleR3Database();

   // Variable to hold the maximum parId
   TD_DatabaseId maxParId;
   maxParId = 9;

   // Variable to hold the lowest illegal parId
   TD_DatabaseId illegalParId;
   illegalParId = 10;

   // Verify correctness of class ID
   if (pDB->getClassId() != ID_SAMPLER3DATABASE)
   {      setTestResult(TEST_FAILURE, "Wrong class ID");
            return;
    }

   // Check that database is not yet configured
   if ( pDB->isObjectConfigured() != NOT_CONFIGURED )
   {      setTestResult(TEST_FAILURE, "Incorrect configuration status at creation");
            return;
    }

   // Configure database
   pDB->setDefaultTable((char*)defaultTable);
   pDB->setOperationalTable((char*)operationalTable);
   pDB->reset();

   // Check that database is configured
   if ( pDB->isObjectConfigured() != CONFIGURED )
   {      setTestResult(TEST_FAILURE, "Incorrect configuration status after configuration was completed");
            return;
   }

   // Check the pointer getter methods
   
   if ((unsigned char*)pDB->getParameterPointerShort(1)!=operationalTable+0)
   {      setTestResult(TEST_FAILURE, "Incorrect pointer value for parameter");
            return;
   }
   if ((unsigned char*)pDB->getParameterPointerUnsignedShort(2)!=operationalTable+8)
   {      setTestResult(TEST_FAILURE, "Incorrect pointer value for parameter");
            return;
   }
   if ((unsigned char*)pDB->getParameterPointerInt(3)!=operationalTable+16)
   {      setTestResult(TEST_FAILURE, "Incorrect pointer value for parameter");
            return;
   }
   if ((unsigned char*)pDB->getParameterPointerUnsignedInt(4)!=operationalTable+24)
   {      setTestResult(TEST_FAILURE, "Incorrect pointer value for parameter");
            return;
   }
   if ((unsigned char*)pDB->getParameterPointerChar(5)!=operationalTable+32)
   {      setTestResult(TEST_FAILURE, "Incorrect pointer value for parameter");
            return;
   }
   if ((unsigned char*)pDB->getParameterPointerUnsignedChar(6)!=operationalTable+40)
   {      setTestResult(TEST_FAILURE, "Incorrect pointer value for parameter");
            return;
   }
   if ((unsigned char*)pDB->getParameterPointerFloat(7)!=operationalTable+48)
   {      setTestResult(TEST_FAILURE, "Incorrect pointer value for parameter");
            return;
   }
   if ((unsigned char*)pDB->getParameterPointerDouble(8)!=operationalTable+56)
   {      setTestResult(TEST_FAILURE, "Incorrect pointer value for parameter");
            return;
   }
   if ((unsigned char*)pDB->getParameterPointerBool(9)!=operationalTable+64)
   {      setTestResult(TEST_FAILURE, "Incorrect pointer value for parameter");
            return;
   }

   // Check that non-real paramaters have the correct value
   
   if (pDB->getParameterShort(1)!=(short)1)
   {      setTestResult(TEST_FAILURE, "Incorrect parameter value");
            return;
   }
   if (pDB->getParameterUnsignedShort(2)!=(unsigned short)2)
   {      setTestResult(TEST_FAILURE, "Incorrect parameter value");
            return;
   }
   if (pDB->getParameterInt(3)!=(int)3)
   {      setTestResult(TEST_FAILURE, "Incorrect parameter value");
            return;
   }
   if (pDB->getParameterUnsignedInt(4)!=(unsigned int)4)
   {      setTestResult(TEST_FAILURE, "Incorrect parameter value");
            return;
   }
   if (pDB->getParameterChar(5)!=(char)5)
   {      setTestResult(TEST_FAILURE, "Incorrect parameter value");
            return;
   }
   if (pDB->getParameterUnsignedChar(6)!=(unsigned char)6)
   {      setTestResult(TEST_FAILURE, "Incorrect parameter value");
            return;
   }
   if (pDB->getParameterBool(9)!=(bool)9)
   {      setTestResult(TEST_FAILURE, "Incorrect parameter value");
            return;
   }

   // Check that real parameters have the correct value
   
   if (fabs(pDB->getParameterFloat(7)-7) > DBL_EPSILON)
   {      setTestResult(TEST_FAILURE, "Incorrect value for parameter");
            return;
   }
   if (fabs(pDB->getParameterDouble(8)-8) > DBL_EPSILON)
   {      setTestResult(TEST_FAILURE, "Incorrect value for parameter");
            return;
   }

   // Update the value of all parameters by setting it equal to their (parId+1)
   
   pDB->setParameter(1,(short)(1+1)); 
   pDB->setParameter(2,(unsigned short)(2+1)); 
   pDB->setParameter(3,(int)(3+1)); 
   pDB->setParameter(4,(unsigned int)(4+1)); 
   pDB->setParameter(5,(char)(5+1)); 
   pDB->setParameter(6,(unsigned char)(6+1)); 
   pDB->setParameter(7,(float)(7+1)); 
   pDB->setParameter(8,(double)(8+1)); 
   pDB->setParameter(9,(bool)(9+1)); 

   // Check that non-real paramaters have the correct value
   
   if (pDB->getParameterShort(1)!=(short)(1+1))
   {      setTestResult(TEST_FAILURE, "Incorrect value for parameter 1");
            return;
   }
   if (pDB->getParameterUnsignedShort(2)!=(unsigned short)(2+1))
   {      setTestResult(TEST_FAILURE, "Incorrect value for parameter 2");
            return;
   }
   if (pDB->getParameterInt(3)!=(int)(3+1))
   {      setTestResult(TEST_FAILURE, "Incorrect value for parameter 3");
            return;
   }
   if (pDB->getParameterUnsignedInt(4)!=(unsigned int)(4+1))
   {      setTestResult(TEST_FAILURE, "Incorrect value for parameter 4");
            return;
   }
   if (pDB->getParameterChar(5)!=(char)(5+1))
   {      setTestResult(TEST_FAILURE, "Incorrect value for parameter 5");
            return;
   }
   if (pDB->getParameterUnsignedChar(6)!=(unsigned char)(6+1))
   {      setTestResult(TEST_FAILURE, "Incorrect value for parameter 6");
            return;
   }
   if (pDB->getParameterBool(9)!=(bool)(9+1))
   {      setTestResult(TEST_FAILURE, "Incorrect value for parameter 9");
            return;
   }

   // Check that real paramaters have the correct value
   
   if (fabs(pDB->getParameterFloat(7)-(7+1)) > DBL_EPSILON)
   {      setTestResult(TEST_FAILURE, "Incorrect value for parameter 7");
            return;
   } 
   if (fabs(pDB->getParameterDouble(8)-(8+1)) > DBL_EPSILON)
   {      setTestResult(TEST_FAILURE, "Incorrect value for parameter 8");
            return;
   } 
   // Check the setter and pointer methods generate event reports when they are accessed either
   // with an out-of-range parameter value or with an illegal parameter value
   if (isNonNominalCheckAllowed()) {
        char* dummy_1;

        pDB->setParameter(maxParId+1,(int)0);
        if ( !verifyLatestEvent(nEvt+1,EVT_ILLEGAL_DB_ACCESS) )
           return;
        nEvt++;  

        pDB->setParameter(illegalParId,(int)0);
        if ( !verifyLatestEvent(nEvt+1,EVT_ILLEGAL_DB_ACCESS) )
           return;
        nEvt++;  

        dummy_1 = (char*)pDB->getParameterPointerInt(maxParId+1);
        if ( !verifyLatestEvent(nEvt+1,EVT_ILLEGAL_DB_ACCESS) )
            return;
        nEvt++; 

        dummy_1 = (char*)pDB->getParameterPointerInt(illegalParId);
        if ( !verifyLatestEvent(nEvt+1,EVT_ILLEGAL_DB_ACCESS) )
            return;
        nEvt++; 
        pDB->setParameter(maxParId+1,(unsigned int)0);
        if ( !verifyLatestEvent(nEvt+1,EVT_ILLEGAL_DB_ACCESS) )
           return;
        nEvt++;  

        pDB->setParameter(illegalParId,(unsigned int)0);
        if ( !verifyLatestEvent(nEvt+1,EVT_ILLEGAL_DB_ACCESS) )
           return;
        nEvt++;  

        dummy_1 = (char*)pDB->getParameterPointerUnsignedInt(maxParId+1);
        if ( !verifyLatestEvent(nEvt+1,EVT_ILLEGAL_DB_ACCESS) )
            return;
        nEvt++; 

        dummy_1 = (char*)pDB->getParameterPointerUnsignedInt(illegalParId);
        if ( !verifyLatestEvent(nEvt+1,EVT_ILLEGAL_DB_ACCESS) )
            return;
        nEvt++; 
        pDB->setParameter(maxParId+1,(short)0);
        if ( !verifyLatestEvent(nEvt+1,EVT_ILLEGAL_DB_ACCESS) )
           return;
        nEvt++;  

        pDB->setParameter(illegalParId,(short)0);
        if ( !verifyLatestEvent(nEvt+1,EVT_ILLEGAL_DB_ACCESS) )
           return;
        nEvt++;  

        dummy_1 = (char*)pDB->getParameterPointerShort(maxParId+1);
        if ( !verifyLatestEvent(nEvt+1,EVT_ILLEGAL_DB_ACCESS) )
            return;
        nEvt++; 

        dummy_1 = (char*)pDB->getParameterPointerShort(illegalParId);
        if ( !verifyLatestEvent(nEvt+1,EVT_ILLEGAL_DB_ACCESS) )
            return;
        nEvt++; 
        pDB->setParameter(maxParId+1,(unsigned short)0);
        if ( !verifyLatestEvent(nEvt+1,EVT_ILLEGAL_DB_ACCESS) )
           return;
        nEvt++;  

        pDB->setParameter(illegalParId,(unsigned short)0);
        if ( !verifyLatestEvent(nEvt+1,EVT_ILLEGAL_DB_ACCESS) )
           return;
        nEvt++;  

        dummy_1 = (char*)pDB->getParameterPointerUnsignedShort(maxParId+1);
        if ( !verifyLatestEvent(nEvt+1,EVT_ILLEGAL_DB_ACCESS) )
            return;
        nEvt++; 

        dummy_1 = (char*)pDB->getParameterPointerUnsignedShort(illegalParId);
        if ( !verifyLatestEvent(nEvt+1,EVT_ILLEGAL_DB_ACCESS) )
            return;
        nEvt++; 
        pDB->setParameter(maxParId+1,(char)0);
        if ( !verifyLatestEvent(nEvt+1,EVT_ILLEGAL_DB_ACCESS) )
           return;
        nEvt++;  

        pDB->setParameter(illegalParId,(char)0);
        if ( !verifyLatestEvent(nEvt+1,EVT_ILLEGAL_DB_ACCESS) )
           return;
        nEvt++;  

        dummy_1 = (char*)pDB->getParameterPointerChar(maxParId+1);
        if ( !verifyLatestEvent(nEvt+1,EVT_ILLEGAL_DB_ACCESS) )
            return;
        nEvt++; 

        dummy_1 = (char*)pDB->getParameterPointerChar(illegalParId);
        if ( !verifyLatestEvent(nEvt+1,EVT_ILLEGAL_DB_ACCESS) )
            return;
        nEvt++; 
        pDB->setParameter(maxParId+1,(unsigned char)0);
        if ( !verifyLatestEvent(nEvt+1,EVT_ILLEGAL_DB_ACCESS) )
           return;
        nEvt++;  

        pDB->setParameter(illegalParId,(unsigned char)0);
        if ( !verifyLatestEvent(nEvt+1,EVT_ILLEGAL_DB_ACCESS) )
           return;
        nEvt++;  

        dummy_1 = (char*)pDB->getParameterPointerUnsignedChar(maxParId+1);
        if ( !verifyLatestEvent(nEvt+1,EVT_ILLEGAL_DB_ACCESS) )
            return;
        nEvt++; 

        dummy_1 = (char*)pDB->getParameterPointerUnsignedChar(illegalParId);
        if ( !verifyLatestEvent(nEvt+1,EVT_ILLEGAL_DB_ACCESS) )
            return;
        nEvt++; 
        pDB->setParameter(maxParId+1,(bool)0);
        if ( !verifyLatestEvent(nEvt+1,EVT_ILLEGAL_DB_ACCESS) )
           return;
        nEvt++;  

        pDB->setParameter(illegalParId,(bool)0);
        if ( !verifyLatestEvent(nEvt+1,EVT_ILLEGAL_DB_ACCESS) )
           return;
        nEvt++;  

        dummy_1 = (char*)pDB->getParameterPointerBool(maxParId+1);
        if ( !verifyLatestEvent(nEvt+1,EVT_ILLEGAL_DB_ACCESS) )
            return;
        nEvt++; 

        dummy_1 = (char*)pDB->getParameterPointerBool(illegalParId);
        if ( !verifyLatestEvent(nEvt+1,EVT_ILLEGAL_DB_ACCESS) )
            return;
        nEvt++; 
        pDB->setParameter(maxParId+1,(float)0);
        if ( !verifyLatestEvent(nEvt+1,EVT_ILLEGAL_DB_ACCESS) )
           return;
        nEvt++;  

        pDB->setParameter(illegalParId,(float)0);
        if ( !verifyLatestEvent(nEvt+1,EVT_ILLEGAL_DB_ACCESS) )
           return;
        nEvt++;  

        dummy_1 = (char*)pDB->getParameterPointerFloat(maxParId+1);
        if ( !verifyLatestEvent(nEvt+1,EVT_ILLEGAL_DB_ACCESS) )
            return;
        nEvt++; 

        dummy_1 = (char*)pDB->getParameterPointerFloat(illegalParId);
        if ( !verifyLatestEvent(nEvt+1,EVT_ILLEGAL_DB_ACCESS) )
            return;
        nEvt++; 
        pDB->setParameter(maxParId+1,(double)0);
        if ( !verifyLatestEvent(nEvt+1,EVT_ILLEGAL_DB_ACCESS) )
           return;
        nEvt++;  

        pDB->setParameter(illegalParId,(double)0);
        if ( !verifyLatestEvent(nEvt+1,EVT_ILLEGAL_DB_ACCESS) )
           return;
        nEvt++;  

        dummy_1 = (char*)pDB->getParameterPointerDouble(maxParId+1);
        if ( !verifyLatestEvent(nEvt+1,EVT_ILLEGAL_DB_ACCESS) )
            return;
        nEvt++; 

        dummy_1 = (char*)pDB->getParameterPointerDouble(illegalParId);
        if ( !verifyLatestEvent(nEvt+1,EVT_ILLEGAL_DB_ACCESS) )
            return;
        nEvt++; 
    }
    
   // Check the getter methods generate errors when they are accessed either
   // with an out-of-range parameter value or with an illegal parameter value
   if (isNonNominalCheckAllowed()) {
        double dummy_2;

        dummy_2 = (double)pDB->getParameterInt(maxParId+1);
        if ( !verifyLatestEvent(nEvt+1,EVT_ILLEGAL_DB_ACCESS) )
            return;
        nEvt++;  

        dummy_2 = (double)pDB->getParameterInt(illegalParId);
        if ( !verifyLatestEvent(nEvt+1,EVT_ILLEGAL_DB_ACCESS) )
            return;
        nEvt++;  

        dummy_2 = (double)pDB->getParameterUnsignedInt(maxParId+1);
        if ( !verifyLatestEvent(nEvt+1,EVT_ILLEGAL_DB_ACCESS) )
            return;
        nEvt++;  

        dummy_2 = (double)pDB->getParameterUnsignedInt(illegalParId);
        if ( !verifyLatestEvent(nEvt+1,EVT_ILLEGAL_DB_ACCESS) )
            return;
        nEvt++;  

        dummy_2 = (double)pDB->getParameterShort(maxParId+1);
        if ( !verifyLatestEvent(nEvt+1,EVT_ILLEGAL_DB_ACCESS) )
            return;
        nEvt++;  

        dummy_2 = (double)pDB->getParameterShort(illegalParId);
        if ( !verifyLatestEvent(nEvt+1,EVT_ILLEGAL_DB_ACCESS) )
            return;
        nEvt++;  

        dummy_2 = (double)pDB->getParameterUnsignedShort(maxParId+1);
        if ( !verifyLatestEvent(nEvt+1,EVT_ILLEGAL_DB_ACCESS) )
            return;
        nEvt++;  

        dummy_2 = (double)pDB->getParameterUnsignedShort(illegalParId);
        if ( !verifyLatestEvent(nEvt+1,EVT_ILLEGAL_DB_ACCESS) )
            return;
        nEvt++;  

        dummy_2 = (double)pDB->getParameterChar(maxParId+1);
        if ( !verifyLatestEvent(nEvt+1,EVT_ILLEGAL_DB_ACCESS) )
            return;
        nEvt++;  

        dummy_2 = (double)pDB->getParameterChar(illegalParId);
        if ( !verifyLatestEvent(nEvt+1,EVT_ILLEGAL_DB_ACCESS) )
            return;
        nEvt++;  

        dummy_2 = (double)pDB->getParameterUnsignedChar(maxParId+1);
        if ( !verifyLatestEvent(nEvt+1,EVT_ILLEGAL_DB_ACCESS) )
            return;
        nEvt++;  

        dummy_2 = (double)pDB->getParameterUnsignedChar(illegalParId);
        if ( !verifyLatestEvent(nEvt+1,EVT_ILLEGAL_DB_ACCESS) )
            return;
        nEvt++;  

        dummy_2 = (double)pDB->getParameterBool(maxParId+1);
        if ( !verifyLatestEvent(nEvt+1,EVT_ILLEGAL_DB_ACCESS) )
            return;
        nEvt++;  

        dummy_2 = (double)pDB->getParameterBool(illegalParId);
        if ( !verifyLatestEvent(nEvt+1,EVT_ILLEGAL_DB_ACCESS) )
            return;
        nEvt++;  

        dummy_2 = (double)pDB->getParameterFloat(maxParId+1);
        if ( !verifyLatestEvent(nEvt+1,EVT_ILLEGAL_DB_ACCESS) )
            return;
        nEvt++;  

        dummy_2 = (double)pDB->getParameterFloat(illegalParId);
        if ( !verifyLatestEvent(nEvt+1,EVT_ILLEGAL_DB_ACCESS) )
            return;
        nEvt++;  

        dummy_2 = (double)pDB->getParameterDouble(maxParId+1);
        if ( !verifyLatestEvent(nEvt+1,EVT_ILLEGAL_DB_ACCESS) )
            return;
        nEvt++;  

        dummy_2 = (double)pDB->getParameterDouble(illegalParId);
        if ( !verifyLatestEvent(nEvt+1,EVT_ILLEGAL_DB_ACCESS) )
            return;
        nEvt++;  

    }
   
	setTestResult(TEST_SUCCESS,"Test Successful");
	return;
}
