  
//
// Copyright 2004 P&P Software GmbH - All Rights Reserved
//
// DC_SM_PreSepFsmState.cpp
//
// This file was automatically generated by an XSL program

#include "../GeneralInclude/CompilerSwitches.h"
#include "../GeneralInclude/Constants.h"
#include "../FSM/FsmState.h"
#include "../FSM/DC_SM_PreSepFsmState.h"

DC_SM_PreSepFsmState::DC_SM_PreSepFsmState(void) {
      // insert application-specific code here
}
    
    
void DC_SM_PreSepFsmState::doInit(void) {
      FsmState::doInit();
      // remove previous statement and insert application-specific code here
}
    
void DC_SM_PreSepFsmState::doContinue(void) {
      return;
}
          
bool DC_SM_PreSepFsmState::isFinished(void) {
      return FsmState::isFinished();
      // remove previous statement and insert application-specific code here
}
    