  
//
// Copyright 2004 P&P Software GmbH - All Rights Reserved
//
// DC_SCM_FsmState.cpp
//
// This file was automatically generated by an XSL program

#include "../GeneralInclude/CompilerSwitches.h"
#include "../GeneralInclude/Constants.h"
#include "../FSM/FsmState.h"
#include "../FSM/DC_SCM_FsmState.h"

DC_SCM_FsmState::DC_SCM_FsmState(void) {
      // insert application-specific code here
}
    
    
void DC_SCM_FsmState::doInit(void) {
      FsmState::doInit();
      // remove previous statement and insert application-specific code here
}
    
void DC_SCM_FsmState::doContinue(void) {
      return;
      // remove previous statement and insert application-specific code here
}
          
bool DC_SCM_FsmState::isFinished(void) {
      return FsmState::isFinished();
      // remove previous statement and insert application-specific code here
}
    