  
//
// Copyright 2004 P&P Software GmbH - All Rights Reserved
//
// DC_SBY_PostSepFsmState.cpp
//
// This file was automatically generated by an XSL program

#include "../GeneralInclude/CompilerSwitches.h"
#include "../GeneralInclude/Constants.h"
#include "../FSM/FsmState.h"
#include "../FSM/DC_SBY_PostSepFsmState.h"

DC_SBY_PostSepFsmState::DC_SBY_PostSepFsmState(void) {
      // insert application-specific code here
}
    
    
void DC_SBY_PostSepFsmState::doInit(void) {
      FsmState::doInit();
      // remove previous statement and insert application-specific code here
}
    
void DC_SBY_PostSepFsmState::doContinue(void) {
      return;
}
          
void DC_SBY_PostSepFsmState::doExit(void) {
      FsmState::doExit();
      // remove previous statement and insert application-specific code here
}
    
bool DC_SBY_PostSepFsmState::isFinished(void) {
      return FsmState::isFinished();
      // remove previous statement and insert application-specific code here
}
    