  
//
// Copyright 2004 P&P Software GmbH - All Rights Reserved
//
// DC_SBY_PreSepFsmState.cpp
//
// This file was automatically generated by an XSL program

#include "../GeneralInclude/CompilerSwitches.h"
#include "../GeneralInclude/Constants.h"
#include "../FSM/FsmState.h"
#include "../FSM/DC_SBY_PreSepFsmState.h"

DC_SBY_PreSepFsmState::DC_SBY_PreSepFsmState(void) {
      // insert application-specific code here
}
    
    
void DC_SBY_PreSepFsmState::doInit(void) {
      FsmState::doInit();
      // remove previous statement and insert application-specific code here
}
    
void DC_SBY_PreSepFsmState::doContinue(void) {
      return;
}
          
bool DC_SBY_PreSepFsmState::isFinished(void) {
      return FsmState::isFinished();
      // remove previous statement and insert application-specific code here
}
    