  

//
// Copyright 2004 P&P Software GmbH - All Rights Reserved
//
// DC_SampleR3Database_inc.h
//
// This file is automatically generated by an XSL program
//

/**
 * @file DC_SampleR3Database_inc.h 
 * This file defines symbolic names for the parameter identifiers for the
 * parameter database defined in class <code>DC_SampleR3Database</code>.
 * The symbolic names are obtained by capitalizing the name of the database
 * parameter as given in the XML database descriptor file and adding the prefix
 * "DB_" to it.
 * Classes that wish to use symbolic names to access the parameters in the database
 * should include this file. 
 * This file was generated automatically by an XSL program that processes the 
 * XML-based application model.
 * @see DC_SampleR3Database
 */

#ifndef DC_SampleR3Database_incH
#define DC_SampleR3Database_incH

#include "../GeneralInclude/BasicTypes.h"


const TD_DatabaseId DB_P1 = 1;
const TD_DatabaseId DB_P2 = 2;
const TD_DatabaseId DB_P3 = 3;
const TD_DatabaseId DB_P4 = 4;
const TD_DatabaseId DB_P5 = 5;
const TD_DatabaseId DB_P6 = 6;
const TD_DatabaseId DB_P7 = 7;
const TD_DatabaseId DB_P8 = 8;
const TD_DatabaseId DB_P9 = 9;

#endif
