  
//
// Copyright 2004 P&P Software GmbH - All Rights Reserved
//
// DC_AfsFsmState.cpp
//
// This file was automatically generated by an XSL program

#include "../GeneralInclude/CompilerSwitches.h"
#include "../GeneralInclude/Constants.h"
#include "../FSM/FsmState.h"
#include "../FSM/DC_AfsFsmState.h"

DC_AfsFsmState::DC_AfsFsmState(void) {
      // insert application-specific code here
}
    
    
void DC_AfsFsmState::doInit(void) {
      FsmState::doInit();
      // remove previous statement and insert application-specific code here
}
    
void DC_AfsFsmState::doContinue(void) {
      return;
}
          
void DC_AfsFsmState::doExit(void) {
      FsmState::doExit();
      // remove previous statement and insert application-specific code here
}
    