  
//
// Copyright 2004 P&P Software GmbH - All Rights Reserved
//
// DC_SampleMonitoringProfile.cpp
//
// This file was automatically generated by an XSL program

#include "../GeneralInclude/CompilerSwitches.h"
#include "../GeneralInclude/Constants.h"
#include "../FDIR/MonitoringProfile.h"
#include "../FDIR/DC_SampleMonitoringProfile.h"

DC_SampleMonitoringProfile::DC_SampleMonitoringProfile(void) {
      // insert application-specific code here
}
    
bool DC_SampleMonitoringProfile::doProfileCheck(TD_Float value) {
      // insert application-specific code here
      return false;
}

bool DC_SampleMonitoringProfile::doProfileCheck(TD_Integer value) {
      // insert application-specific code here
      return false;
}
            