  
//
// Copyright 2004 P&P Software GmbH - All Rights Reserved
//
// DC_SampleRecoveryAction.cpp
//
// This file was automatically generated by an XSL program

#include "../GeneralInclude/CompilerSwitches.h"
#include "../GeneralInclude/Constants.h"
#include "../FDIR/RecoveryAction.h"
#include "../FDIR/DC_SampleRecoveryAction.h"

DC_SampleRecoveryAction::DC_SampleRecoveryAction(void) {
      // insert application-specific code here
}
    
TD_ActionOutcome DC_SampleRecoveryAction::doRecoveryAction(void) {
      // insert application-specific code here
      return ACTION_SUCCESS;
}
            