

  
//
// Copyright 2003 P&P Software GmbH  - All Rights Reserved
//
// CC_IntStack.h
//
// Version	1.0
// Date		30.08.03 (Version 1.0)
// Author	A. Pasetti (P&P Software)
//

#ifndef CC_IntStackH
#define CC_IntStackH

#include "../GeneralInclude/ForwardDeclarations.h"
#include "../GeneralInclude/BasicTypes.h"
#include "../Base/CC_RootObject.h"


/**
 * Stack-like container class for items of type: <code>int</code>. 
 * This class was automatically generated by an XSLT program.
 * It models a FIFO container with a fixed size. The items in the container are
 * handled as variables of type: <code>int</code>. This is 
 * a type-safe class that does not perform any type casting.
 * The size of the stack must be set by the user during the initialization phase
 * and cannot be changed afterwards. This class offers the two traditional <i>push</i>
 * and <i>pop</i> operations and a <i>reset</i> operation that empties the stack.
 * Attempts to push a full stack or to pop an empty stack result in no action other
 * than the generation of an event report.
 * @author Alessandro Pasetti (P&P Software)
 * @version 1.0
 */
class CC_IntStack : public CC_RootObject {

  private:
    unsigned int size;		
    unsigned int stackPointer;	// index of next free location on stack		
    int* pStack;     // Array of pointers to the items in the stack.

  public:

    /**
     * Instantiate a new stack container.
     * The stack is initially empty. Its size is set to an illegal value to 
     * signify that the stack is not yet configured.
     */
    CC_IntStack();

    /**
     * Push an item onto the stack.
     * If the stack is already full, no action is taken but event report
     * EVT_STACK_FULL is generated to report the fact. Users should always check that the
     * stack is not full (using operation <code>isFull</code>) before performing
     * a push operation. 
     * @see TD_EventType
     * @param newItem the new item to be added to the stack
     */
    void push(int newItem);

    /**
     * Pop an item from the stack.
     * If the stack is empty, the value of NULL is returned and event report
     * EVT_STACK_FULL is generated to report the fact. Users should always check that the
     * stack is not empty (using operation <code>isEmpty</code>) before performing
     * a pop operation. 
     * @see TD_EventType
     * @return the most recently item pushed onto the stack or NULL if the stack is 
     * empty
     */
    int pop();

    /**
     * Set the size of the stack. The size of the stack is the maximum number of
     * items that can be held by the stack. A call to this method causes the internal 
     * FIFO data structure where the stack items are stored to be created and initialized.
     * <p>
     * This is an initialization method. It should be called before the
     * stack is used for the first time and it should not be called more
     * than once. Attempts to call it more than once will result in memory leaks.
     * It is not legal to set the repository size to 0.     
     * @param size the desired size of the stack
     */
    void setStackSize(unsigned int size);

    /**
     * Return the size of the stack.      
     * @see #setStackSize
     * @return the desired size of the stack
     */
    unsigned int getStackSize() const;

    /**
     * Return the number of items currently on the stack.      
     * @return the number of items currently on the stack
     */
    unsigned int getNumberOfItems() const;

    /**
     * Check whether the stack is emtpy
     * @return true if the stack is emtpy, false otherwise
     */
    bool isEmpty() const;

    /**
     * Check whether the stack is full
     * @return true if the stack is full, false otherwise
     */
    bool isFull() const;

    /**
     * Reset the stack.
     * The stack is brought back to the status it had after it was
     * configured but before it was ever used.
     */
    void reset();

    /**
     * Perform a class-specific configuration check on a stack object:
     * verify that the stack size
     * has a legal value.
     * @return true if the object is configured, false otherwise
     */
    virtual bool isObjectConfigured();

};

#endif


