  
//
// Copyright 2003 P&P Software GmbH - All Rights Reserved
//
// DC_SampleR2Database.c
//
// This file was automatically generated by an XSL program
//

#include "../GeneralInclude/CompilerSwitches.h"
#include "../GeneralInclude/DebugSupport.h"
#include "../GeneralInclude/BasicTypes.h"
#include "../GeneralInclude/ClassId.h"
#include "../GeneralInclude/Constants.h"
#include "../Base/CC_RootObject.h"
#include "DC_SampleR2Database.h"

static unsigned int const CharCode = 1;
static unsigned int const UnsignedCharCode = 2;
static unsigned int const ShortCode = 3;
static unsigned int const UnsignedShortCode = 4;
static unsigned int const IntCode = 5;
static unsigned int const UnsignedIntCode = 6;
static unsigned int const BoolCode = 7;
static unsigned int const FloatCode = 8;
static unsigned int const DoubleCode = 9;



///////////////////////////////////////////////////////////////////////////////
//
//                  non-virtual member method(s) definition
//
///////////////////////////////////////////////////////////////////////////////

{
   assert( pOperTable != pNULL );
   pOperationalTable = pOperTable;
}
{
   assert( pDefTable != pNULL );
   pDefaultTable = pDefTable;
}
void DC_SampleR2Database_setDefaultTable(DC_SampleR2Database *This, char* pDefTable)

void DC_SampleR2Database_setOperationalTable(DC_SampleR2Database *This, char* pOperTable)

